project:
  type: book

book:
  title: Macroeconomics I
  author:
    - name: 柳本和春
      email: yanagimoto@econ.kobe-u.ac.jp
      orcid: 0009-0007-1967-8304
      affiliations:
        - name: 神戸大学
  date: last-modified
  site-url: https://kazuyanagimoto.com/course-kobe-macro1-2025
  repo-url: https://github.com/kazuyanagimoto/course-kobe-macro1-2025
  favicon: static/img/logo_circle.svg
  twitter-card:
    image: static/img/sns-card.drawio.png
    card-style: summary_large_image
    creator: kazuyanagimoto
  open-graph:
    image: static/img/sns-card.drawio.png
    locale: ja_JP
  sidebar:
    logo: static/img/logo_transparent.svg
    search: false
  

bibliography: references.bib
bibliography-style: chicago-author-year

profile:
  group:
    - [html, pdf]

execute:
  freeze: auto

crossref:
  fig-title: "図"
  fig-prefix: "図"
  tbl-title: "表"
  tbl-prefix: "表"
  eq-title: "式"
  eq-prefix: "式"
  thm-title: "定理"
  thm-prefix: "定理"
  prp-title: "命題"
  prp-prefix: "命題"
  lem-title: "補題"
  lem-prefix: "補題"
  exm-title: "例"
  exm-prefix: "例"
