project:
  output-dir: _book
  resources:
    - Macroeconomics-I.pdf
    - static/schedule.csv

book:
  chapters: 
    - index.qmd
    - text: RBC Model
      file: 01-rbc.qmd
    - text: New Keynesian
      file: 02-nk.qmd
    - text: DMP Framework
      file: 03-dmp.qmd
  appendices: 
    - 11-linearization.qmd
    - 12-proofs.qmd
    - 13-foundation.qmd
    - 14-labor-supply.qmd
    - references.qmd

format:
  html:
    lightbox: true
    code-tools: true
    theme:
      - brand
    highlight-style: atom-one
