[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
MacroModelling = "687ffad2-3618-405e-ac50-e0f7b9c75e44"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProjectRoot = "e3f974f6-674d-4b8e-a3d1-5850677db852"
QuantEcon = "fcd29c91-0bd7-5a09-975d-7ac3f643a60c"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
SummaryTables = "6ce4ecf0-73a7-4ce3-9fb4-80ebfe887b60"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
